### ISSUE TITLE
Admob npa

### ISSUE THREAD

**Issue by linked67** [mopub/mopub-ios-mediation#160]
1. **What is the issue?**

Documentation not clear about Admob npa

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [ x] I searched https://developers.mopub.com/ and found no answer.
    - [ x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [ x] I searched the adapter changelogs to make sure this issue has not already been resolved.

3. **Fill in the below template as detailed as possible:**
   
Documentation say to add code below IF the user does not consent to receive personalized ads:

    MPGoogleGlobalMediationSettings *mediationSettings = [[MPGoogleGlobalMediationSettings alloc] init];
    mediationSettings.npa = @"1";

Can we use canCollectPersonalInfo BEFORE the SDK init to know if user consent or not, is it the good way to do ?

    if ([[MoPub sharedInstance] canCollectPersonalInfo]) {
        sdkConfig.globalMediationSettings = @[];
    }else{
        MPGoogleGlobalMediationSettings *mediationSettings = [[MPGoogleGlobalMediationSettings alloc] init];
        mediationSettings.npa = @"1";
        sdkConfig.globalMediationSettings = [[NSArray alloc] initWithObjects:mediationSettings, nil];
    }

**Comment by chauduyphanvu1** [comment]
Using `canCollectPersonalInfo` before the SDK initialization is not recommended, because you need the SDK initialization to finish to determine whether GDPR applies (`isGDPRApplicable` would be `MPBoolUnknown` otherwise) , which influences what `canCollectPersonalInfo` is. Querying `canCollectPersonalInfo` that way, therefore, does not necessarily give you the most up-to-date information.

You should be getting the user consent first (via Google's consent management mechanism), then determine what should be passed for the `npa`. Then, initialize MoPub and pass the `MPGoogleGlobalMediationSettings` instance. Once MoPub has initialized, display the MoPub's consent dialog to collect the user consent for MoPub. Let us know if there are any questions!

Vu Chau
MoPub SDK Team

**Comment by linked67** [comment]
Ok it's more clear now, the Admob consent should come from the Admob consent dialog. That's not very cool to display two dialog (Admob and Mopub), it's too much.

If i don't provide globalMediationSettings (emprty array), is it the same as npa set to 1 or 0 ?

I'll try to just keep the Mopub consent dialog and still display Admob.

**Comment by chauduyphanvu1** [comment]
On iOS, the `npa` only gets forwarded to AdMob if it's non-empty: https://github.com/mopub/mopub-ios-mediation/blob/master/AdMob/MPGoogleAdMobBannerCustomEvent.m#L72-L76. In that case, it does not matter what value that String has.

**Comment by linked67** [comment]
Ok, thanks a lot
