### ISSUE TITLE
Spec works incorrect. 'MPBaseAdapterConfiguration.h' file not found for -Adapters

### ISSUE THREAD

**Issue by 1Podoshva** [mopub/mopub-ios-mediation#163]
When I try to install these versions for adapters:
_pod 'MoPub-AdMob-Adapters', '7.36.0.0'
pod 'MoPub-Vungle-Adapters', '6.3.2.0'
pod 'MoPub-AdColony-Adapters', '3.3.5.0'
pod 'MoPub-Applovin-Adapters', '5.1.2.0'
pod 'MoPub-FacebookAudienceNetwork-Adapters', '5.1.0.0'
pod 'MoPub-UnityAds-Adapters', '3.0.0.0'_

Terminal logs:
Installing MoPub-AdColony-Adapters (3.3.5.0)
Installing MoPub-AdMob-Adapters (7.36.0.0)
Installing MoPub-Applovin-Adapters (5.1.2.0)
Installing MoPub-FacebookAudienceNetwork-Adapters (5.1.0.0)
Installing MoPub-UnityAds-Adapters (3.0.0.0)
Installing MoPub-Vungle-Adapters (6.3.2.0)

and this version MoPub SDK:
_pod 'mopub-ios-sdk', '5.4.0'_

I have the issue **'MPBaseAdapterConfiguration.h' file not found** for all _NAME_AdapterConfiguration.h. Investigated it and I see what cocoapods install the incorrect versions for all adapters. For example, 'MoPub-AdMob-Adapters' adapterVersion is "7.37.0.4", 'MoPub-Vungle-Adapters' adapterVersion is "5.1.0.4". 
This leads to a project does not build because mopub-ios-sdk 5.4.0 doesn't have 'MPBaseAdapterConfiguration.h, it was added in mopub-ios-sdk 5.5.0.

At the moment we can not update to the latest versions for adapters and mopub ios sdk. We have the version dependencies with other SDKs.

**Comment by chauduyphanvu1** [comment]
This happens because the versions of pods you are fetching are from before the time our podspecs were [converted to using tags](https://github.com/mopub/mopub-ios-mediation/commit/441be9a9b765e20f6564faef1673819d18c3d62d#diff-4838a6094950c42d53ed78b005618f84). Only versions higher than those would fetch the correct adapter versions. Versions that are older or the same as the ones in that commit will always get the latest adapter code from the master branch on this repository, which includes the `-AdapterConfiguration.h/.m` files. This is an intended behavior by CocoaPods.

To work around this, if you don't intend to use CocoaPods and `xcodebuild` for validation later on, we suggest [locating past commits](https://github.com/mopub/mopub-ios-mediation/commits/master) that contain the correct versions of the adapters you are intending to integrate. If you really need to use CocoaPods, let us know and we can make a one-off exception by pushing the versions you are looking to new releases.

Vu Chau
MoPub SDK Team

**Comment by 1Podoshva** [comment]
@chauduyphanvu1
Thanks for clarifying. We added all adapters manually and it works for us.
