### ISSUE TITLE
implementation of `setAdvertiserTrackingEnabled`for FB Audience network

### ISSUE THREAD

**Issue by amsdamsgram** [mopub/mopub-ios-mediation#361]
1. **What is the issue?**
    According to Facebook Audience Network, with the new rules from Apple and iOS 14, we will need to set the advertiser tracking to true and they also specify:
>If you are using mediation, then you need to implement the setAdvertiserTrackingEnabled flag before initializing the mediation SDK in order for us to receive it in the bidding request.

Source: https://developers.facebook.com/docs/audience-network/guides/advertising-tracking-enabled

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved.

Do you have any plan to implement it?
If yes, how should we use it?

Thank you,

**Comment by chauduyphanvu** [comment]
@amsdamsgram, because this is a contract between publishers and the Facebook Audience Network SDK, we currently do not plan to support passing the `setAdvertiserTrackingEnabled` flag via the mediation adapters. 

You will need to call that API directly from your app code. One way would be to call the `setAdvertiserTrackingEnabled` API some time before initializing the MoPub SDK. 

Let us know if there are any questions!

Vu Chau
MoPub Team
