### ISSUE TITLE
Older versions of the IronSourceSDK causes pod install to fail with a 403

### ISSUE THREAD

**Issue by djk12587** [mopub/mopub-ios-mediation#399]
1. **What is the issue?**
    > Run a pod install with an older version of ironsource like '7.0.3.0.2' and use pod 'mopub-ios-sdk', '5.15.0'.

2. **Check the applicable box(es) below by placing an `x` in the brackets:**
    - [x] I searched https://developers.mopub.com/ and found no answer.
    - [x] I searched https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed. 
    (I dont use twitter)
    - [x] I searched the adapter changelogs to make sure this issue has not already been resolved. 
    (new versions install correctly, but our app uses ironsource  '7.0.3.0.2' which is broken)

3. **Fill in the below template as detailed as possible:**
    * **Platform** (*Android, iOS, Unity*)
        > iOS
    * **MoPub SDK Version**
        > 5.15.0
    * **Mediation SDK Name & Version**
        > 'MoPub-IronSource-Adapters', '7.0.3.0.2'
    * **Mediation Adapter Version**
        > 'MoPub-IronSource-Adapters', '7.0.3.0.2'
    * **Steps to reproduce the issue** (include integration steps if not standard)
        > 1. Setup a podfile with 'mopub-ios-sdk', '5.15.0' & 'MoPub-IronSource-Adapters', '7.0.3.0.2'
        > 2. run "pod install"
    * **Observed behavior**
        > see cocoapods 403 error on console
    * **Expected behavior** (if known)
        > install without failures
    * **Evidence** (if available)
        > Below is the log from cocoapods
```
[!] Error installing IronSourceSDK
[!] /usr/bin/curl -f -L -o /var/folders/2n/_8nhvfyn5j7dcprhzj6hj5m80000gp/T/d20210607-93504-1sz20gl/file.zip https://dl.bintray.com/ironsource-mobile/ios-sdk/IronSource7.1.5.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
```

**Comment by chauduyphanvu** [comment]
@djk12587, it looks like this is because ironSource has physically removed historical versions of their SDK from production. 

If you go to the podspec (https://github.com/CocoaPods/Specs/blob/master/Specs/7/7/b/IronSourceSDK/7.0.3.0/IronSourceSDK.podspec.json), the `source` link (https://dl.bintray.com/ironsource-mobile/ios-sdk/IronSource7.0.3.zip) no longer works. That causes CocoaPods to fail to get the SDK whose version was transitively linked to by the mediation adapters. There is nothing that can be done from MoPub.

To integrate an old ironSource SDK version, alternatively check out their GitHub: https://github.com/ironsource-mobile/iOS-sdk.

Vu Chau
MoPub Team

**Comment by djk12587** [comment]
annoying, but thanks for replying
