### ISSUE TITLE
Problem with Facebook audience network integration

### ISSUE THREAD

**Issue by SodaSurfer** [mopub/mopub-ios-mediation#408]
I am trying to integrate FAN ads for bidding, using Mopub integration.
I have created my ad spaces and did all the setup that I needed to do in the FAN console and also in Mopub console as instructed in here: https://developers.mopub.com/publishers/ui/manage-advanced-bidding/
and in here: https://developers.facebook.com/docs/audience-network/bidding/partner-mediation/mopub

I think that there is something wrong in my code implementation.
I am using swiftui and I have initialized Facebook ads and Mopub ads like so when my app launches:

```
ATTrackingManager.requestTrackingAuthorization(completionHandler: { status in
    Analytics.logEvent(AppConsts.FBA_EVENT_TRACK_AUTH, parameters: [AppConsts.FBA_PARAM_TRACK_STATUS: String(status.rawValue)])
    
    // used for FBA
    FBAudienceNetworkAds.initialize(with: nil, completionHandler: nil)
    switch (status) {
    case .authorized:
        FBAdSettings.setAdvertiserTrackingEnabled(true)
        break
    case .denied, .notDetermined, .restricted:
        FBAdSettings.setAdvertiserTrackingEnabled(false)
        break
    @unknown default:
        FBAdSettings.setAdvertiserTrackingEnabled(false)
        break
    }
    
    // Tracking authorization completed. Start loading ads here.
    // Initialize Mopub
    let sdkConfig = MPMoPubConfiguration(adUnitIdForAppInitialization: AdsId.BANNER_ID.value)
    sdkConfig.loggingLevel = .info
    MoPub.sharedInstance().initializeSdk(with: sdkConfig)
})
```

Now, I do get ad requests from Mopub and I see the data in Mopub console, but I don't get any response from Facebook and I get this error showing on Facebook audience network console:
`"We haven't received a bid request"`

am I missing something in the code integration?
The examples here aren't updated to swiftui and for bidding, therefore I assume I am missing something.

thanks

**Comment by chauduyphanvu** [comment]
@chauduyphanvu, have you tried testing with test ads? You can do that by calling `FBAdSettings.addTestDevice(FBAdSettings.testDeviceHash())`. Remember to remove that code when you are ready to publish your app. 

You might also want to add your Facebook placement IDs to the [FBAdInitSettings ](https://developers.facebook.com/docs/audience-network/reference/ios/classes/fbadinitsettings.html)when you call `FBAudienceNetworkAds.initialize(with: FBAdInitSettings , completionHandler: nil)`. 

I'd also recommend chaining your method calls, so that it is guaranteed the code executes linearly. Initialize Facebook --> Wait for completion handler --> Call `FBAdSettings.setAdvertiserTrackingEnabled` --> Initialize MoPub --> Wait for completion handler --> Request ads.

Vu Chau
MoPub Team

**Comment by SodaSurfer** [comment]
@chauduyphanvu thanks for answering.
I don't have a test device, I'm working on a macOS with m1, and my apps are currently on production (and as I said, showing only Mopub ads, and not Facebook, not sure why). is it mandatory to test it first with a test device?

I want to try and add "FBAdInitSettings" as you mentioned, but I need for that the exact string to pass as a"mediationService" to init that class. you know what is the exact string that I need to pass when working with Mopub? 

thanks

**Comment by chauduyphanvu** [comment]
@SodaSurfer, a test device is not necessary/mandatory but it is a good way to confirm whether the issue is device-specific or placement-/account-specific. Also, you do not need a test device to receive test ads. You just need to call the Facebook test APIs I listed in my previous response to see if you get any ads. If you do, then you can rest assured that your SDK/adapters integration is OK, and that the issue might be with the placement/account setup on the Facebook side.

You can follow/replicate this code snippet that the mediation adapter itself uses: https://github.com/mopub/mopub-ios-mediation/blob/a40dd6a90f15d4d82b108dc21c5b8ff6c567f984/FacebookAudienceNetwork/FacebookAdapterConfiguration.m#L80-L96. 

If you still encounter issues, feel free to share your console logs and/or ad unit IDs here and I can also check from our test environment.

**Comment by SodaSurfer** [comment]
> @SodaSurfer, a test device is not necessary/mandatory but it is a good way to confirm whether the issue is device-specific or placement-/account-specific. Also, you do not need a test device to receive test ads. You just need to call the Facebook test APIs I listed in my previous response to see if you get any ads. If you do, then you can rest assured that your SDK/adapters integration is OK, and that the issue might be with the placement/account setup on the Facebook side.
> 
> You can follow/replicate this code snippet that the mediation adapter itself uses:
> 
> https://github.com/mopub/mopub-ios-mediation/blob/a40dd6a90f15d4d82b108dc21c5b8ff6c567f984/FacebookAudienceNetwork/FacebookAdapterConfiguration.m#L80-L96
> 
> .
> If you still encounter issues, feel free to share your console logs and/or ad unit IDs here and I can also check from our test environment.

@chauduyphanvu thank you for your help. I'm still having issue displaying Facebook ads, and only the Mopub ads are showing in my app.
I don't feel comfortable to write here my ads IDs, is it possible I'll send it to you in some kind of email account or any other private way?

thanks

**Comment by chauduyphanvu** [comment]
@SodaSurfer, sure, please DM me on [Twitter](https://twitter.com/chauduyphanvu). Thanks!

**Comment by chauduyphanvu** [comment]
Discussions happened via Twitter DM. The culprit of the issue is still likely on the serving side from the Facebook placement IDs. 

Feel free to reopen the issue if you need additional assistance!

**Comment by djrobinson999** [comment]
Hi I am having the same problem and have tried the above but still no requests are sent to Facebook. Bidding requests ARE sent to Mopub Marketplace tho. How can I tell where the messages are getting lost ? Can I check on the client side ?
