### ISSUE TITLE
Podspecs should include a `LICENSE` file

### ISSUE THREAD

**Issue by rob-keepsafe** [mopub/mopub-ios-mediation#81]
## Issue

When running `pod install` with mopub pods, it seems quite a few of them are missing a `LICENSE` file in the source that's bundled.

<img width="797" alt="screen shot 2018-08-13 at 12 37 38 pm" src="https://user-images.githubusercontent.com/30269720/44045199-cdddecb6-9ef5-11e8-982e-d1c348431e2a.png">

## How to fix

For each podspec, ensure the code directory that is downloaded via `pod install` has a `LICENSE` file included in it. This could mean including it with the source code, or adding a `LICENSE` file to the root of the repo (it depends on how you're specifying the source).

**Comment by rsatrasala** [comment]
Thank you for the recommendations @rob-keepsafe. We will look into this shortly.

**Comment by altairdeark** [comment]
@rsatrasala, any updates?

**Comment by rsatrasala** [comment]
Hello @altairdeark we have tried few ways to add LICENSE file including the ways @rob-keepsafe recommended. But we continue to see the warnings because mopub-ios-mediation repository is associated with multiple pods which is not the usual scenario. We are continuing to work on removing these warnings.

Having said that, since this is a warning that does not impact functionality, we do not have this prioritized immediately. We will update this issue as soon as we have a resolution.

**Comment by rsatrasala** [comment]
Hello all, We have finally resolve this issue. Thanks for the inputs @rob-keepsafe.

Installing current adapters may still show warning but the new pods created from today should not have the same behavior.
